server:
  port:  9081

spring:
  datasource:
    username: scott
    password: scott
    url: jdbc:postgresql://localhost:5432/example
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
