server:
  port:  9081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false

spring:
  datasource:
    username: scott
    password: scott
    url: jdbc:postgresql://localhost:5432/example
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update